### ISSUE TITLE
Entrega

### ISSUE THREAD

**Issue by smaraggi** [Gonb4/paradigmas_2c2024#4]
Hola chicos, por favor especifiquen la entrega en qué rama y condición queda para corrección. Gracias.

**Comment by smaraggi** [comment]
Hola chicos, sigo sin tener respuesta a este comentario sobre la entrega. Les pido que me aclaren cuando hayan entregado en qué rama y condición queda el trabajo para su revisión. Gracias.

**Comment by Gonb4** [comment]
Hola Santiago, ya está la entrega en la rama tp1. Saludos.

**Comment by smaraggi** [comment]
Hola chicos, tienen aprobado el TP con 7 (siete).

El archivo POM está mal generado porque apunta a una ruta de la máquina de uno de ustedes. Entre ustedes se habrán arreglado modificándolo localmente, pero no es la manera de subirlo al repo porque luego otro lo baja y ya no le anda.

Lo arreglé para poder corregir, pero además les paso cómo sería por ejemplo para no usar un path específico:

En el archivo pom, plugins, javafx, reemplazar esto que tenían ustedes:
```
<!--
                <configuration>
                    <mainClass>Juego</mainClass>
                    <executable>C:\Users\Gon\.jdks\openjdk-23\bin\java.exe</executable>
                </configuration>
                -->
```

Por por ejemplo esto:
```
<executions>
    <execution>
        <!-- Default configuration for running -->
        <!-- Usage: mvn clean javafx:run -->
        <id>default-cli</id>
        <configuration>
            <mainClass>Juego</mainClass>
        </configuration>
    </execution>
</executions>
```

La programación del modelo está muy bien. Realmente prolija la separación en clases. Tienen algunos errores, como que Localidad entienda algo de colisiones. Ese es un error de separación de incumbencias o de nombre de la clase. Si la clase representa una locación ocupable, deberían ser los ocupantes los que implementan el comportamiento de colisión, y no la localidad tener conocimiento de un caso especial; esto se debería legar al ocupante que sabe qué hacer con esa colisión. Esto sería basándonos en el principio de "single responsability class", uno de los más importantes, se trata de que una clase sea responsable de una sola cosa.

La parte de la vista está muy bien resuelta también. Podrían haber separado en un poco más de clases pero la complejidad del problema permitía un poco lo que hicieron. Está bien resuelto. En cuanto a la organización del código se suele separar en carpetas al menos vista y modelo. Ustedes tienen clases separadas pero todo en una misma carpeta. No lo consideré "mal", pero está mejor separar en capas las aplicaciones, cuando crecen eso es un lío sino. Tienen bien separadas las incumbencias de vista y modelo. No usaron MVC pero tampoco era un requisito.

Felicitaciones y saludos. Doy por cerrado este issue y entrega, les recomiendo dejar este repo mergeado a su rama principal para mejor referencia a futuro cuando lo quieran abrir y correr, no se dejan las cosas terminadas en branches sueltos.

Saludos.
