### ISSUE TITLE
Entrega TP2 (individual)

### ISSUE THREAD

**Issue by Gonb4** [Gonb4/paradigmas_2c2024#5]
Qué tal, Santiago? Ya está en la rama tp2 la entrega completa. 

(Actualicé el readme con mis datos pero los dejo acá también por si acaso)

Nombre: Gonzalo Bustos
Padrón: 100827

Saludos!

**Comment by smaraggi** [comment]
Hola Gonzalo, el TP te queda aprobado con 10, felicitaciones.

Podés mergear ambas ramas y dejar en master ambos TPs resueltos.
